# Generated by Django 2.1.3 on 2019-03-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='to_address',
        ),
        migrations.AddField(
            model_name='address',
            name='is_flagged_for_saturation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='subscription.Address'),
        ),
    ]
