# Generated by Django 2.1.3 on 2019-03-22 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20190316_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('public_key', models.TextField(default='')),
                ('long_key_id', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_external',
        ),
    ]
