# Generated by Django 2.1.3 on 2019-03-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20190322_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_payment_confirmed',
        ),
    ]
