# Generated by Django 2.1.3 on 2019-03-30 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_subscription_is_payment_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('matter', models.TextField(default='', verbose_name='The main body of the announcement')),
                ('signature', models.TextField(default='', verbose_name='The signature of the system for this announcement')),
                ('is_active', models.BooleanField(default=False)),
                ('date_activated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='public_key',
            field=models.TextField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='encrypted_content',
            field=models.TextField(default='', verbose_name='The secret content of the challenge encrypted to the public key of the user. Decrypt this content using your secret key.'),
        ),
        migrations.AlterField(
            model_name='system',
            name='long_key_id',
            field=models.CharField(default='', max_length=255, verbose_name='The GPG long key id corresponding to the public key'),
        ),
        migrations.AlterField(
            model_name='system',
            name='public_key',
            field=models.TextField(default='', verbose_name='The GPG public key of the system'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='subscription.System'),
        ),
    ]
