# Generated by Django 2.1.3 on 2019-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20190330_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='private_key',
            field=models.TextField(default='', verbose_name='The GPG private key of the system'),
        ),
    ]
