# Generated by Django 2.1.3 on 2019-05-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_system_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='disclaimer',
            field=models.TextField(default='', verbose_name='The disclaimer'),
        ),
        migrations.AddField(
            model_name='system',
            name='disclaimer_signature',
            field=models.TextField(default='', verbose_name='The disclaimer signature'),
        ),
        migrations.AddField(
            model_name='system',
            name='guarantee',
            field=models.TextField(default='', verbose_name='The Transactino guarantee'),
        ),
        migrations.AddField(
            model_name='system',
            name='guarantee_signature',
            field=models.TextField(default='', verbose_name='The guarantee signature'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.Address'),
        ),
    ]
