# Generated by Django 2.1.3 on 2019-06-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20190520_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
