
class schema_constants:
  ATTRIBUTES = 'attributes'
  RELATIONSHIPS = 'relationships'
  METHODS = 'methods'
  INSTANCES = 'instances'
  INTERNAL_QUERYSET = 'internal_queryset'
  EXTERNAL_QUERYSETS = 'external_querysets'
  SORT = 'sort'
  PAGINATE = 'paginate'
  TEMPORARY_IDS = 'temporary_ids'
  ADD = 'add'
  REMOVE = 'remove'
  NULL = 'null'
  RUN = 'run'
