# Generated by Django 2.1.3 on 2019-02-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereport',
            name='pending_block_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
