# Generated by Django 2.1.3 on 2019-03-24 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20190322_0816'),
        ('transactino', '0002_feereport_pending_block_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('block_hash', models.CharField(max_length=64)),
                ('txid', models.CharField(max_length=64)),
                ('index', models.PositiveIntegerField(default=0)),
                ('value', models.PositiveIntegerField(default=0)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('is_active', models.BooleanField(default=False)),
                ('target_address', models.CharField(max_length=255)),
                ('value_equal_to', models.PositiveIntegerField(null=True)),
                ('value_greater_than', models.PositiveIntegerField(default=0)),
                ('value_less_than', models.PositiveIntegerField(null=True)),
                ('latest_block_hash', models.CharField(default='', max_length=64)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_reports', to='subscription.Account')),
            ],
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='transaction_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='transactino.TransactionReport'),
        ),
    ]
