# Generated by Django 2.0.4 on 2018-11-14 01:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('value', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressPrototype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('parent', models.CharField(max_length=64)),
                ('height', models.PositiveIntegerField(default=0)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlockPrototype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('txid', models.CharField(max_length=64)),
                ('value', models.BigIntegerField(default=0)),
                ('index', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('addresses', models.ManyToManyField(related_name='deltas', to='bitcoin.Address')),
            ],
        ),
        migrations.CreateModel(
            name='DeltaPrototype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('txid', models.CharField(max_length=64)),
                ('index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('txid', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bitcoin.Block')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPrototype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('txid', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='delta',
            name='from_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_deltas', to='bitcoin.Transaction'),
        ),
        migrations.AddField(
            model_name='delta',
            name='to_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_deltas', to='bitcoin.Transaction'),
        ),
    ]
